/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_walterfan_gtd_util_MessageBus */

#ifndef _Included_com_github_walterfan_gtd_util_MessageBus
#define _Included_com_github_walterfan_gtd_util_MessageBus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_walterfan_gtd_util_MessageBus
 * Method:    sendMessage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_github_walterfan_gtd_util_MessageBus_sendMessage
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
